global:
  message: Welcome to global Microservice environment.
logging:
  level:
    root: INFO
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        inculde: health, info, refresh
  endpoint:
    health:
      show-details: always
