global:
  message: Welcome to customer service dev enviornment!
server:
  port: 8082
message: Hello From Dev!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cust_dev
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
