global:
  message: Welcome to order service dev enviornment!
server:
  port: 8084
message: Hello From Dev!
spring:
  datasource:
    url: jdbc:h2:mem:order_master
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
