global:
  message: Welcome to order service dev enviornment!
server:
  port: 8084
message: Hello From Dev!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_dev
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
